export const SYSTEM_ROLES = {
  ADMIN: "ADMIN",
  KOORDINATOR_POSKO: "KOORDINATOR_POSKO",
  PETUGAS: "PETUGAS",
};

export const OFFICER_TYPES = {
  PETUGAS_POSKO: "PETUGAS_POSKO",
  PETUGAS_ASSESSMENT: "PETUGAS_ASSESSMENT",
  PETUGAS_AMBULANCE: "PETUGAS_AMBULANCE",
};

export const USER_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
};

export const INCIDENT_STATUS = {
  REPORTED: "REPORTED",
  ON_PROCESS: "ON_PROCESS",
  HANDLED: "HANDLED",
  CLOSED: "CLOSED",
};
